(@::def-pkg '((:NAME . "al-plate")
        (:FULL-NAME . "铝板")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.4")
        (:LOCALE . "chs")
        (:CATEGORY . "机械")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "铝板展开")
        (:URL . "http://atlisp.cn")
        (:FILES "al-plate")))
