(@:def-pkg '((:NAME . "at-3d")
        (:FULL-NAME . "@lisp 3D相关")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.2")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "3D相关，曲面，实体相关工具")
        (:URL . "http://atlisp.cn")
        (:FILES "at-3d")))
