(@::def-pkg '((:NAME . "everything")
        (:FULL-NAME . "Everything")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.8")
        (:LOCALE . "chs")
        (:CATEGORY . "APP")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "基于名称快速定位文件和文件夹。")
        (:URL . "http://atlisp.cn")
        (:FILES "everything")))
