#+title:Everything
* Everything
** "Everything" 是什么？
"Everything" 是 Windows 上一款搜索引擎，它能够基于文件名快速定文件和文件夹位置。

不像 Windows 内置搜索，"Everything" 默认显示电脑上每个文件和文件夹 (就如其名 "Everything")。

您在搜索框输入的关键词将会筛选显示的文件和文件夹。


** "Everything" 索引全部文件需要多长时间？
"Everything" 仅索引文件和文件夹名，一般仅需几秒便可建立其数据库。

全新安装的 Windows 10 (大约 120,000 个文件) 仅需 1 秒即可索引完成。

索引 1,000,000 个文件将需要大约 1 分钟。


** "Everything" 能否搜索文件内容？
可以，"Everything" 可以通过搜索函数 content: 来搜索文件内容。

文件内容未被索引时，搜索内容将会很慢。


** "Everything" 是否占用很多系统资源？
不，"Everything" 仅需要使用非常少的系统资源。

全新安装的 Windows 10 (大约 120,000 个文件) 仅需要大约 14 MB 的内存以及不到 9 MB 的硬盘空间。

1,000,000 个文件需要大约 75 MB 的内存和 45 MB 的硬盘空间。


** "Everything" 能否监控文件系统变更？
可以，"Everything" 可以监控文件系统变更。

搜索结果就可以反映出文件系统变更。


** "Everything" 免费么？
免费，"Everything" 是一款免费软件。

软件开发维护不易，请考虑捐赠。


** "Everything" 是否包含恶意、间谍软件或广告？
完全没有，"Everything" 不包含任何恶意、间谍软件或广告。


** "Everything" 在非运行时是否会丢失文件系统变更？
不会，"Everything" 在关闭和重新打开中不会丢失文件系统变更 (甚至系统重启也不会)。

"Everything" 将在启动后更新数据库。


** "Everything" 的系统要求是什么？
"Everything" 能在 Windows XP、Vista、Windows 7、Windows 8 和 Windows 10 上运行。

NTFS 索引功能需要 Everything 服务或用管理员方式打开 "Everything"。


** 怎么样转换分卷为 NTFS？
转换分卷为 NTFS前，请务必备份好任何重要资料。

分卷一旦转换为 NTFS，它将无法转换回 FAT 或 FAT32。

请注意，某些系统可能无法读取 U 盘或 USB 中 NTFS 分卷。


转换分卷为 NTFS：

开始菜单，点击运行。

输入以下内容并点击确定：

cmd
在命令提示符中，输入以下内容并点击确定：

convert D: /fs:ntfs
其中 D: 是待转换分区。


** "Everything" 能否可以索引映射的网络分区？
可以，请查阅文件夹索引以获取更多信息。


** 如何安装 "Everything"？
请查阅 "Everything" 基础安装指南。


** 如何使用 "Everything"？
请查阅 "Everything" 基础使用指南。


** 为何 "Everything" 1.4 比 1.3 占用更多内存？
"Everything" 1.4 默认索引了文件大小和日期并存储了额外信息以便更快排序。

请查阅最小内存优化以禁用这些变更。


** 如何在运行 "Everything" 时屏蔽 UAC 警告？
"Everything" 需要管理员权限以便低级别读取 NTFS 分卷来 NTFS 索引。


UAC 警告可以通过以标准用户运行 "Everything" 和安装 "Everything" 服务或不使用 NTFS 索引来避免。


以标准用户运行 "Everything" 和安装 "Everything" 服务：

在 "Everything" 中，打开工具菜单，点击选项。

点击常规页面。

检查 Everything 服务。

取消以管理员方式运行。

点击确定。

退出 "Everything" (右键 Everything 托盘图标并点击退出)。

重启 Everything。




搜索

** 如何搜索文件或文件夹？
在搜索框中输入文件或文件夹部分名称，搜索结果将会立即出现。


** 如何使用布尔运算符？
AND 是默认布尔运算符。


例如，搜索 abc 和 123，您可以：

abc 123

搜索两个搜索项中任意一个，在两项中加上 | 。


例如，搜索 .jpg 或 .bmp，您可以：

.jpg | .bmp

搜索时排除某项，在其开头加上 ! 。


例如，搜索除了 abc 以外的内容，您可以：

!abc

查看 Everything 基础搜索语法：

在 "Everything" 中，打开帮助菜单，点击搜索语法。


** 如何使用通配符？
搜索关键词中使用通配符 * 将会匹配任意数量的任意字符。

例如，搜索以 e 开头并以 g 结尾的文件和文件夹：e*g

搜索关键词中使用通配符 ? 将会匹配任一字符。

例如，搜索含有两个字符扩展名的文件：*.??


** 如何搜索包含空格的关键词？
搜索包含空格的关键词，请用双引号。

例如，搜索关键词 foo<space>bar："foo bar"


** 如何搜索文件类型？
搜索文件类型，请在搜索框输入扩展名，

例如，搜索 mp3 文件，输入 *.mp3 即可。

搜索多个文件类型，请使用 | 分隔，

例如：*.bmp|*.jpg 将会搜索 bmp 或 jpg 类型文件。


** 如何搜索指定位置的文件和文件夹？
搜索指定位置的文件和文件夹，请在搜索框中使用 \。

例如，在 downloads 文件夹中搜索全部 mp3 文件：downloads\ .mp3

您也可以在搜索菜单中启用匹配路径并包含路径到搜索关键词中。

例如，启用匹配路径并在 downloads 文件夹中搜索全部 avi 文件：downloads .avi


** 高级搜索
查阅 Everything 帮助以获取更多信息。




疑难解答

** 搜索结果不对
请确认以下搜索选项未选择：

在 Everything 中，打开搜索菜单：

取消大小写匹配。

取消全字匹配。

取消匹配路径。

取消匹配变音标记。

取消启用正则表达式。


请确认 Everything 筛选器：

在 Everything 中，打开搜索菜单：

检查 Everything。


** 设置未保存
请确认已启用保存设置和数据到 %APPDATA%\Everything。


启用保存设置和数据到 %APPDATA%\Everything：

在 Everything 中，打开工具菜单，点击选项。

点击常规页面。

点击保存设置和数据到 %APPDATA%\Everything。

点击确定。


** 结果重复
"Everything" 已自动索引 NTFS 分卷。

添加 NTFS 分卷作为文件夹索引将会导致搜索结果重复。


移除作为文件夹索引的 NTFS 分卷：

在 Everything 中，打开工具菜单，点击选项。

点击文件夹页面

选择 NTFS 分卷并点击移除。

点击确定。


检查 NTFS 分卷是否被自动索引：

在 Everything 中，打开工具菜单，点击选项。

点击 NTFS 页面。

数据库中 NTFS 分卷必定包含在 NTFS 索引中。


** 搜索结果为空或仅包含分区
请确认 "Everything" 服务已运行或 "Everything" 以管理员身份运行。


安装 "Everything" 服务：

在 Everything 中，打开工具菜单，点击选项。

点击常规页面。

点击 Everything 服务：

点击确定。


-或-


以管理员身份运行 Everything：

在 Everything 中，打开工具菜单，点击选项。

点击常规页面。

点击管理员身份运行：

点击确定。


请确认您拥有至少一个本地 NTFS 分卷。

请查阅转换分卷为 NTFS。


手动启用索引全部本地 NTFS 分卷：

在 Everything 中，打开工具菜单，点击选项。

点击 NTFS 页面。

分卷列表中的本地 NTFS 分卷：

检查包含到数据库。

检查启用 USN 日志记录。

检查监控变更。

点击确定。


强制 Everything 重建数据库：

在 Everything 中，打开工具菜单，点击选项。

点击索引页面。

点击强制重建。

点击确定。
