(@::def-pkg '((:NAME . "ole")
        (:FULL-NAME . "ole图像")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.5")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "将图像文件以OLE方式插入到dwg中")
        (:URL . "http://atlisp.cn")
        (:FILES "ole"
            "install.ps1")))
