(@:def-pkg '((:NAME . "at-session")
        (:FULL-NAME . "@lisp会话管理")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.1.8")
        (:LOCALE . "zh")
        (:CATEGORY . "Efficiency tools")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "用于管理当前或历史打开的多个dwg文档，一次打开多个关联的dwg文档。")
        (:URL . "http://atlisp.cn")
        (:FILES "at-session")))
