(@:def-pkg '((:NAME . "align-all")
        (:FULL-NAME . "对齐图素")
        (:AUTHOR . "print1985")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.6")
        (:LOCALE . "CHS")
        (:CATEGORY . "通用")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "源自 print1985 。对选中的图素调整行距。支持CAD文字、天正单行和多行文字、图块、属性字、天正标高、cad表格、cad尺寸")
        (:URL . "http://atlisp.cn")
        (:REQUIRED . "base")
        (:FILES "align-all")))
