(@::def-pkg '((:NAME . "autohotkey")
        (:FULL-NAME . "AutoHotKey")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.3")
        (:LOCALE . "CHS")
        (:CATEGORY . "APP")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:FREE . T)
        (:DESCRIPTION . "AutoHotKey(AHK):是简易而功能强大的热键脚本语言。使用者可将键盘、鼠标甚至游戏摇杆的移动和点击动作记录下来。")
        (:URL . "http://atlisp.cn")
        (:FILES "autohotkey")))
