(@:def-pkg '((:NAME . "at-color")
        (:FULL-NAME . "@lisp Color")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.9")
        (:LOCALE . "CHS")
        (:CATEGORY . "Color")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "modify color of entity or layer, remove true color")
        (:URL . "http://atlisp.cn")
        (:FILES "at-color")))
