(@:def-pkg '((:NAME . "at-color")
        (:FULL-NAME . "@lisp颜色")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.8")
        (:LOCALE . "CHS")
        (:CATEGORY . "颜色相关")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "改对象或图层颜色,去真彩色")
        (:URL . "http://atlisp.cn")
        (:FILES "at-color")))
