(@:def-pkg '((:NAME . "at-dim")
        (:FULL-NAME . "标注")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.8")
        (:LOCALE . "CHS")
        (:CATEGORY . "标注")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "标注斜率，线长等")
        (:URL . "http://atlisp.cn")
        (:FILES "at-dim")))
