(@:def-pkg '((:NAME . "doslib")
        (:FULL-NAME . "DosLib")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.7")
        (:LOCALE . "CHS")
        (:CATEGORY . "Lib")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "DosLib 扩展工具,根据CAD运行环境，下载相匹配的arx,不用下载全部文件。")
        (:URL . "http://atlisp.cn")
        (:FILES "doslib")))
