(@:def-pkg '((:NAME . "at-xdata")
        (:FULL-NAME . "@lisp扩展数据管理")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.2")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "用于查看和修改 dwg 中的扩展数据。")
        (:URL . "http://atlisp.cn")
        (:FILES "at-xdata")))
