(@::def-pkg '((:NAME . "at-number")
        (:FULL-NAME . "编号工具")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.6")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "给图形编号，如矩形，圆，以及其它相同的图形，图块等。")
        (:URL . "http://atlisp.cn")
        (:FILES "at-number")))
