(@::def-pkg '((:NAME . "at-planning")
        (:FULL-NAME . "规划")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.7")
        (:LOCALE . "chs")
        (:CATEGORY . "建筑工程")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "规划设计相关功能。规划指标的计算汇总等。")
        (:URL . "http://atlisp.cn")
        (:FILES "at-planning")))
