(@:def-pkg '((:NAME . "at-cnc")
        (:FULL-NAME . "@CNC测试版")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.6")
        (:LOCALE . "chs")
        (:CATEGORY . "机械")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "生成G code,用于CNC加工")
        (:URL . "http://atlisp.cn")
        (:FILES "at-cnc")))
