(@:def-pkg '((:NAME . "at-validate")
        (:FULL-NAME . "@lisp包验证工具")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.1.0")
        (:LOCALE . "chs")
        (:CATEGORY . "开发工具")
        (:REQUIRED . "base")
        (:OPENSOURCE . 1)
        (:DESCRIPTION . "运行时包验证工具：括号匹配检查、未定义函数检测、重复定义检测、依赖检查等。")
        (:URL . "http://atlisp.cn")
        (:FILES "at-validate")))
