(@:def-pkg '((:NAME . "qrencode")
        (:FULL-NAME . "QR二维码生成")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.7")
        (:LOCALE . "chs")
        (:CATEGORY . "图档管理")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "生成二维码，并用多段线绘制到 dwg中。")
        (:URL . "http://atlisp.cn")
        (:FILES "qrencode")))
