(@:def-pkg '((:NAME . "xgjmtxcx")
        (:FULL-NAME . "型钢截面特性")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.3")
        (:LOCALE . "chs")
        (:CATEGORY . "结构")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "型钢截面特性查询工具")
        (:URL . "http://atlisp.cn")
        (:FILES "xgjmtxcx")))
