(@::def-pkg '((:NAME . "composing")
        (:FULL-NAME . "排版")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.7")
        (:LOCALE . "chs")
        (:CATEGORY . "排版")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:FREE . T)
        (:DESCRIPTION . "各种排版")
        (:URL . "http://atlisp.cn")
        (:FILES "composing"
            "cluster-composing")))
