(@:def-pkg '((:NAME . "at-curve")
        (:FULL-NAME . "@lisp曲线")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.4")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "与线有关的工具集")
        (:URL . "http://atlisp.cn")
        (:FILES "at-curve")))
