(@:def-pkg '((:NAME . "aigc")
        (:FULL-NAME . "AIGC")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.2")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "根据描述的条件生成内容,AIGC,生成式人工智能(测试版)")
        (:URL . "http://atlisp.cn")
        (:FILES "aigc")))
