(@:def-pkg '((:NAME . "sidebar")
        (:FULL-NAME . "侧边栏")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.15")
        (:LOCALE . "CHS")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "CAD侧边栏")
        (:URL . "http://atlisp.cn")
        (:FILES "sidebar"
            "CAD_ScreenMenu.dll")))
