(@::def-pkg '((:NAME . "at-purge")
        (:FULL-NAME . "图面清理")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.7")
        (:LOCALE . "CHS")
        (:CATEGORY . "文件")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "图面清理-DGN，分解多重块，炸多重块")
        (:URL . "http://atlisp.cn")
        (:FILES "at-purge")))
