(@::def-pkg '((:NAME . "boundary")
        (:FULL-NAME . "边界分析")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.5")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "生成图形所在闭合区域的边界，填充边界等。")
        (:URL . "http://atlisp.cn")
        (:FILES "boundary")))
