(@:def-pkg '((:NAME . "at-stat")
        (:FULL-NAME . "统计表格")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.5")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "统计图元，并绘制表格。")
        (:URL . "http://atlisp.cn")
        (:FILES "at-stat"
            "menus")))
