(@:def-pkg '((:NAME . "list-rec-wxh")
        (:FULL-NAME . "统计矩形宽高")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.12")
        (:LOCALE . "CHS")
        (:CATEGORY . "定向开发")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "列出正交矩形宽高表.矩形包括倒角或圆角矩形，缺一角或两个角的矩形。")
        (:URL . "http://atlisp.cn")
        (:FILES "list-rec-wxh")))
