(@:def-pkg '((:NAME . "mark-order")
        (:FULL-NAME . "字串编号")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.3")
        (:LOCALE . "chs")
        (:CATEGORY . "定向开发")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "在特定文本上方显示编号，支持单行文本、多行文本、属性值、块内文本、天正门窗")
        (:URL . "http://atlisp.cn")
        (:FILES "mark-order")))
