(@:def-pkg '((:NAME . "base")
        (:FULL-NAME . "@lisp function-lib")
        (:VERSION . "1.5.52")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:DESCRIPTION . "Base package, include some funcition for math,draw,string,datetime,layer,entity,curve,pickset etc.")
        (:CATEGORY . "Lib")
        (:OPENSOURCE . 1)
        (:LICENSES . "LGPL")
        (:URL . "http://atlisp.cn")
        (:FILES "base"
		"plot")))
