(@::def-pkg '((:NAME . "alt-run")
        (:FULL-NAME . "ALTRun")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.3")
        (:LOCALE . "CHS")
        (:CATEGORY . "APP")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:FREE . T)
        (:DESCRIPTION . "ALTRun 是一款快速启动软件，小巧绿色，简单易用。精致简洁的操作界面、精巧灵动的智能匹配、疾如雷电的响应速度和行云流水般畅快淋漓的操控体验的完美结合，足以令人爱不释手。")
        (:URL . "http://atlisp.cn")
        (:FILES "alt-run")))
