#+TITLE: AltRun 

* 软件简介
  ALTRun可以通过右键发送到的方式添加快捷键。

  并且拥有一些有趣的玩法：调整音量，一键启动多个程序，划词搜索(拷贝词语后，快捷键打开翻译页面)，整合 Everything 搜索(这个很神)等等比较复杂的综合性应用实例。


* 软件特色
  LTRun自带的界面皮肤是浅色调的银灰渐变样式，还有个透明质感的黑色皮肤
** 界面讲解
   热键呼出软件主界面后，光标会自动定位在界面左上角输入框内前端处，可以输入英文字母筛选过虑列表清单，输入框右后方显现的浅灰色文字是智能随机的操作提示。

   居于界面中部的白色背景主体大框里显示快捷项目列表清单。左侧半部前头带数字的便是快捷项，右侧半部是与之一一对应的描述名称，两者均可凭个人喜好随心所欲的定制。

   主界面底部命令框显示当前快捷项目的命令行，此框可以设置隐藏。

* 使用说明
  ALTRun独创性的支持主热键和辅热键这种双热键并行不悖、独一无二的呼出呼入方法，喜欢单手启动程序朋友们有福了!据我的使用经验，建议修改主热键设置成Alt+X，将辅热键设置成~键(键盘左上角Esc键下面那个)，基本上只用一只左手就可以搞定任意程序、文档、目录和网页的快捷启动。

  OK，现在按~键(或者自主设定的主辅热键)，立刻呼出主界面(若是随后再次按击自主设定的主辅热键则会隐藏主界面)。

  呈现在眼前的主界面清单列表支持多种方式执行快捷项目：
  1. 空格键或者回车键执行所在行快捷项(左手单手掌控时按空格远比回车键方便顺手、舒适惬意)。
  2. 通过按击数字键执行快捷项，数字键1 2 3 4 5 6 7 8 9 0, 0 代表10，分别启动对应的第一至第十个菜单列表项目(喜欢数字键启动风格的朋友请注意不要在快捷项中加入数字，以免多有不便，不喜欢数字键风格的朋友可以不必理会)。此外，直接按下空格键或回车键也能启动第一项，第二项还可按：键启动，第三项还可按”键启动。
  3. 按照提示区指示的Alt+数字键或者Ctrl+数字键快速启动快捷项。
  4. 鼠标左键双击启动快捷项。
  5. 在主界面窗体内任何位置按击鼠标中键滑轮也可启动引导定位所在行的快捷项。
  6. 特为推荐超级简便的一种执行方法需要设定一下实现，只要勾选配置中的仅剩一项时立即执行(段末图解)，敲击字母过滤后自动执行剩余的唯一一项匹配快捷项(无需按下空格键或者回车键启动)。


  一指热键(~键)呼出主界面，屈指弹向任意数字键，便可启动十个程序中的任意一个程序。全程只要按两下，耗时0.5秒左右，快捷绝伦，疾如雷电。关于该如何设置，让自己心仪的快捷项目出现在热键呼出后优先显示的前十项可供数字键快速启动的默认列表清单中，请参详后文附录A的第三点内容。

  支持数字键启动真是好东西，可视化清单类快捷启动软件中在这一点上能够和ALTRun差相比拟的唯有Find and Run Robot，可惜Find and Run Robot资源占用居高不下，响应迟缓，乏善可陈。若是不太在意资源占用而注重功能的可延展性，插件丰富的Find and Run Robot则是上佳的选择。
  
  不喜欢数字键启动风格的朋友建议使用汉语拼音全拼(容易记忆)设定快捷项，通常敲入三两个字母，就能直接命中目标。要是没命中，待选的顶多就只剩2项，余下的事情也就极为简单了。

  要是你觉得还不过瘾，还有一种最为简便的启动快捷项的方式，只要你敲击一两个英文字母，甚至不需要你按下空格键或者回车键就可自动执行只余一项的匹配项!凤毛麟角，超乎想象，一蹴而就，傲视群伦，在目前的快捷启动软件中也算是独领风骚了!设置方法如下图解所示。

** 迅捷方便的定位方法
   ALTRun主界面列表清单支持多种定位方法：上下箭头键移动定位前后项目;Tab键轮换定位下一个快捷项目(按下Shift+Tab键显示上一项快捷项);最为好玩的是支持鼠标滑轮滑动定位项目。三者皆可周而复始，循环往复!

   键盘达人大概会选择上下箭头键移动定位或者Tab键，不过本人觉得有时候用用鼠标滑轮也很爽快，因为滚轮定位比较迅速，耗费的力气最小，定位完成后按击空格键或者按击鼠标中键滑轮便可启动快捷项。左手键盘，右手鼠标，左右开弓，相得益彰。
