(@::def-pkg '((:NAME . "saw-blade")
        (:FULL-NAME . "锯片")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.5")
        (:LOCALE . "chs")
        (:CATEGORY . "机械")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "绘制锯片")
        (:URL . "http://atlisp.cn")
        (:FILES "saw-blade")))
