(@:def-pkg '((:NAME . "cmd-ext")
        (:FULL-NAME . "命令扩展")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.4")
        (:LOCALE . "chs")
        (:CATEGORY . "Common")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "扩展命令行，命令行支持基本绘图的汉字命令，输入汉字或拼音即可绘图。")
        (:URL . "http://atlisp.cn")
        (:FILES "cmd-ext")))
