(@::def-pkg '((:NAME . "at-arch")
        (:FULL-NAME . "@建筑")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.7")
        (:LOCALE . "chs")
        (:CATEGORY . "建筑工程")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "建筑相关功能，车位编号统计等")
        (:URL . "http://atlisp.cn")
        (:FILES "at-arch")))
