(@:def-pkg '((:NAME . "route-of-hole2shape")
        (:FULL-NAME . "铣削路径")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.16")
        (:LOCALE . "chs")
        (:CATEGORY . "定向开发")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "绘制 圆孔到边线的刀路。以及圆(多段线拟合的圆)自身的刀路。")
        (:URL . "http://atlisp.cn")
        (:FILES "route-of-hole2shape")))
